Algoritmo "conversor"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 22/02/2026
Var
// Seção de Declarações das variáveis 
   angulo, s:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreva("Digite um angulo: ")
 leia(angulo)
 s <- sen(grauprad(angulo))
 escreva("O seno do angulo ", angulo, " é ", s)

Fimalgoritmo